# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_actor_role_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
