# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year_released',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_released',
            field=models.DateField(null=True),
        ),
    ]
