# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_auto_20170923_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
