# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_actor_name_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
