# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_auto_20171023_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name_path',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
